### PR TITLE
Added Repo: Functional Programming Learning Path

### PR DESCRIPTION
**Pull request by yazaldefilimone**
add [repo](https://github.com/imteekay/functional-programming-learning-path) of @imteekay

### CODE REVIEW

**Review by imteekay — APPROVED** [review]
🎉

**Comment by imteekay** [comment]
😞

**Comment by yazaldefilimone** [comment]
> 😞

Hei @imteekay, sorry about that I ended up deleting some repos on my github and I didn't check if I had already done the merge or not

**Comment by imteekay** [comment]
No worries man! Thanks for opening it again :)

**Pull request closed without merging**
